---
- name: Install pigz
  apt:
    name: pigz
    state: present

- name: get /bin/gzip status
  stat:
    path: /bin/gzip
  register: gzip

#- name: Debug
#  debug:
#    msg: "{{ gzip }}"

- name: Set pigz as gzip command
  shell: "mv /bin/gzip /bin/gzip.old && ln -s /usr/bin/pigz /bin/gzip"
  when: not gzip.stat.islnk|bool
