---
- name: Install smartmontools
  apt:
    name: smartmontools
    state: present

- name: Copy /etc/smartd.conf configuration file
  template:
    src: "etc/smartd.conf.j2"
    dest: "/etc/smartd.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart smartmontools
