---
- name: Add custom sysctls
  copy:
    dest: "/etc/sysctl.d/{{ item.filename }}.conf"
    content: "{{ item.content }}"
  with_items: "{{ systools_custom_sysctl }}"

- name: reload sysctl values
  shell: sysctl --system
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
